<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE dwwm_2021 [
    <!ELEMENT <dwwm_2021> (prenom+, nom, age, genre?, site_perso?, info_confinement, info_dev)>
    <!-- DTD pour la civilité -->
    <!ELEMENT prenom (#PCDATA)>
    <!ELEMENT nom (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT genre (masculin|feminin) >
    <!ELEMENT masculin EMPTY >
    <!ELEMENT feminin EMPTY >
    <!ELEMENT site_perso (#PCDATA)>
    <!-- DTD pour le confinement-->
    <!ELEMENT info_confinement (nombre_de_personne, lieu)>
    <!ELEMENT nombre_de_personne (nombre_adulte, nombre_enfant?)>
    <!ELEMENT nombre_adulte (#PCDATA)>
    <!ELEMENT nombre_enfant (#PCDATA)>
    <!ELEMENT lieu (commune, type, surface, jardin)>
    <!ELEMENT commune (#PCDATA)>
    <!ELEMENT type (#PCDATA) >
    <!ELEMENT surface (#PCDATA) >
    <!ELEMENT jardin (jardin_presence, jardin_surface?) >
    <!ELEMENT jardin_presence (#PCDATA)>
    <!ELEMENT jardin_surface (#PCDATA) >
    <!-- DTD pour lales infos de dev -->
    <!ELEMENT info_dev (langage_deja_utilise*, nombre_de_site_developpe?, exemple_de_site_developpe?)>
    <!ELEMENT langage_deja_utilise (XML | HTML | CSS | SASS | LESSCSS | BOOTSTRAP | MATERIALIZE | FOUNDATION | JS | TYPESCRIPT | COFFEESCRIPT | JQUERY | ANGULARJS | NODEJS | REACTJS | VUEJS | ANGULAR | PHP | SYMFONY | LARAVEL | WORDPRESS )*>
    <!ELEMENT XML EMPTY >
    <!ELEMENT HTML EMPTY >
    <!ELEMENT CSS EMPTY >
    <!ELEMENT SASS EMPTY >
    <!ELEMENT LESSCSS EMPTY >
    <!ELEMENT BOOTSTRAP EMPTY >
    <!ELEMENT MATERIALIZE EMPTY >
    <!ELEMENT FOUNDATION EMPTY >
    <!ELEMENT JS EMPTY >
    <!ELEMENT TYPESCRIPT EMPTY >
    <!ELEMENT COFFEESCRIPT EMPTY >
    <!ELEMENT JQUERY EMPTY >
    <!ELEMENT ANGULARJS EMPTY >
    <!ELEMENT NODEJS EMPTY >
    <!ELEMENT REACTJS EMPTY >
    <!ELEMENT VUEJS EMPTY >
    <!ELEMENT ANGULAR EMPTY >
    <!ELEMENT PHP EMPTY >
    <!ELEMENT SYMFONY EMPTY >
    <!ELEMENT LARAVEL EMPTY >
    <!ELEMENT RUBY-ON-RAILS EMPTY >
    <!ELEMENT WORDPRESS EMPTY >
    <!ELEMENT nombre_de_site_developpe (#PCDATA) >
    <!ELEMENT exemple_de_site_developpe (#PCDATA) >
]>

<dwwm_2021>
  <prenom>Andranik</prénom>
  <nom>HAKOBYAN</nom>
  <age>25</age>
  <genre>masculin</genre>
  <info_confinement>
    <nombre_de_personne>
      <nombre_adulte>3</nombre_adulte>
    </nombre_de_personne>
    <lieu>
      <commune>Saint-Etienne</commune>
      <type>appartement</type>
      <surface>70m2</surface>
      <jardin>
        <jardin_presence>OUI</jardin_presence>
      </jardin>
    </lieu>
  </info_confinement>
  <info_dev>
    <langage_deja_utilise>
      <HTML />
      <CSS />
      <SASS />
      <JS />
      <BOOTSTRAP/>
      <NODEJS/>
      <REACTJS/>
      <PHP/>
      <RUBY-ON-RAILS/>
    </langage_deja_utilise>
  </info_dev>
</dwwm_2021> 